on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: python
    steps:
      - run: echo "TESTING"
      - run: python --version
      - uses: actions/checkout@v3
      - run: python script.py